INTERVAL=10
DEVPATH=hwmon3=devices/platform/nct6775.656
DEVNAME=hwmon3=nct6776
FCTEMPS=hwmon3/device/pwm1=hwmon3/device/temp2_input hwmon3/device/pwm2=hwmon3/device/temp2_input hwmon3/device/pwm3=hwmon3/device/temp2_input
FCFANS=hwmon3/device/pwm1=hwmon3/device/fan1_input hwmon3/device/pwm2=hwmon3/device/fan2_input hwmon3/device/pwm3=hwmon3/device/fan3_input
MINTEMP=hwmon3/device/pwm1=45 hwmon3/device/pwm2=45 hwmon3/device/pwm3=45
MAXTEMP=hwmon3/device/pwm1=62 hwmon3/device/pwm2=62 hwmon3/device/pwm3=62
MINSTART=hwmon3/device/pwm1=100 hwmon3/device/pwm2=100 hwmon3/device/pwm3=100
MINSTOP=hwmon3/device/pwm1=26 hwmon3/device/pwm2=26 hwmon3/device/pwm3=26
MINPWM=hwmon3/device/pwm1=26 hwmon3/device/pwm2=26 hwmon3/device/pwm3=26
MAXPWM=hwmon3/device/pwm1=255 hwmon3/device/pwm2=255 hwmon3/device/pwm3=255
